package mars.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javafx.stage.FileChooser;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.filechooser.FileFilter;
import mars.http.HTTPStatus;
import mars.http.ServerUtils;
import mars.utils.Config;
import mars.utils.Logger;
import mars.utils.Website;
import mars.utils.XMLFile;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Stavros Skourtis
 */
public class ServerOptions extends javax.swing.JFrame {

    private int nextConnection = 0;
    private DefaultListModel pageListModel = new DefaultListModel();
    private DefaultListModel blackListModel = new DefaultListModel();

    /**
     * Creates new form ServerOptions
     */
    public ServerOptions() throws IOException {
        initComponents();

        /*
         Updates connections tab every 1 second
         */
        final Timer timer = new Timer(1000, null);
        
        timer.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (nextConnection < Logger.connections.size()) {
                    for (; nextConnection < Logger.connections.size(); nextConnection++) {
                        ipField.setText(ipField.getText() + Logger.connections.get(nextConnection).getIp() + "<br>");
                        portField.setText(portField.getText() + String.valueOf(Logger.connections.get(nextConnection).getPort()) + "<br>");
                        requestField.setText(requestField.getText() + Logger.connections.get(nextConnection).getRequestline() + "<br>");
                        responseField.setText(responseField.getText() + Logger.connections.get(nextConnection).getResponseCode() + "<br>");
                    }
                }
            }
        });
        
        timer.start();

        /*
         Load which methods are allow from config
         */
        getCheckBox.setSelected(Config.GET);
        postCheckBox.setSelected(Config.POST);
        headCheckBox.setSelected(Config.HEAD);
        traceCheckBox.setSelected(Config.TRACE);
        optionsCheckBox.setSelected(Config.OPTIONS);
        deleteCheckBox.setSelected(Config.DELETE);
        putCheckBox.setSelected(Config.PUT);
        connectCheckBox.setSelected(Config.CONNECT);

        /*
         Load php from config
         */
        phpEnable.setSelected(Config.PHP_ENABLED);
        phpPathTextfield.setText(Config.PHP_PATH);

        /*
         Load default pages from config
         */
        for (String page : Config.DEFAULT_PAGES) {
            pageListModel.addElement(page);
        }

        /*
         Load black list from config
         */
        for (String page : Config.BLACK_LIST) {
            blackListModel.addElement(page);
        }

        /*
         Load websites from config
         */
        for (Website site : Config.WEBSITES) {
            websiteTabPane.addTab(String.valueOf(site.getId()) + "::" + site.getPort(), new WebsitePanel(site.getPath(), site.getPort(), site.isSsl(), site.isOnline(), site.getId(), site.getSslFile(), site.getSslPass()));
        }

        versionLabel.setText(HTTPStatus.SERVER_NAME);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        getCheckBox = new javax.swing.JCheckBox();
        postCheckBox = new javax.swing.JCheckBox();
        traceCheckBox = new javax.swing.JCheckBox();
        connectCheckBox = new javax.swing.JCheckBox();
        headCheckBox = new javax.swing.JCheckBox();
        optionsCheckBox = new javax.swing.JCheckBox();
        putCheckBox = new javax.swing.JCheckBox();
        deleteCheckBox = new javax.swing.JCheckBox();
        saveMethodsButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        defaultPageList = new javax.swing.JList(pageListModel);
        defaultFileTextField = new javax.swing.JTextField();
        addDefaultFileNameButton = new javax.swing.JButton();
        removeDefaultFileNameButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        saveDefaultNamesButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        phpPathTextfield = new javax.swing.JTextField();
        phpBrowseButton = new javax.swing.JButton();
        phpEnable = new javax.swing.JCheckBox();
        savePHPSettings = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        websiteTabPane = new javax.swing.JTabbedPane();
        saveSites = new javax.swing.JButton();
        addNewSiteButton = new javax.swing.JButton();
        removeSiteButton = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        blackListList = new javax.swing.JList(blackListModel);
        removeBlackListItemButton = new javax.swing.JButton();
        saveBlackListButton = new javax.swing.JButton();
        ipPart1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ipPart2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ipPart4 = new javax.swing.JTextField();
        ipPart3 = new javax.swing.JTextField();
        addBlackListItemButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        responseField = new javax.swing.JLabel();
        requestField = new javax.swing.JLabel();
        ipField = new javax.swing.JLabel();
        portField = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();

        setTitle("HTTP Server Configuration");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Methods allowed");

        getCheckBox.setText("GET");
        getCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getCheckBoxActionPerformed(evt);
            }
        });

        postCheckBox.setText("POST");

        traceCheckBox.setText("TRACE");

        connectCheckBox.setText("CONNECT");
        connectCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectCheckBoxActionPerformed(evt);
            }
        });

        headCheckBox.setText("HEAD");

        optionsCheckBox.setText("OPTIONS");
        optionsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsCheckBoxActionPerformed(evt);
            }
        });

        putCheckBox.setText("PUT");

        deleteCheckBox.setText("DELETE");

        saveMethodsButton.setText("Save");
        saveMethodsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMethodsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(optionsCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(putCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteCheckBox))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(traceCheckBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(connectCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(getCheckBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(postCheckBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(headCheckBox))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveMethodsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getCheckBox)
                    .addComponent(postCheckBox)
                    .addComponent(headCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(traceCheckBox)
                    .addComponent(connectCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionsCheckBox)
                    .addComponent(putCheckBox)
                    .addComponent(deleteCheckBox))
                .addGap(18, 18, 18)
                .addComponent(saveMethodsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setViewportView(defaultPageList);

        defaultFileTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultFileTextFieldActionPerformed(evt);
            }
        });

        addDefaultFileNameButton.setText("Add");
        addDefaultFileNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDefaultFileNameButtonActionPerformed(evt);
            }
        });

        removeDefaultFileNameButton.setText("Remove");
        removeDefaultFileNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDefaultFileNameButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Default File Names");

        saveDefaultNamesButton.setText("Save");
        saveDefaultNamesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDefaultNamesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(defaultFileTextField)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addDefaultFileNameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveDefaultNamesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeDefaultFileNameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(removeDefaultFileNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveDefaultNamesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addDefaultFileNameButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(defaultFileTextField))
                .addContainerGap())
        );

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("PHP Settings");

        jLabel10.setText("Path");

        phpBrowseButton.setText("Browse");
        phpBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phpBrowseButtonActionPerformed(evt);
            }
        });

        phpEnable.setText("Enable");

        savePHPSettings.setText("Save");
        savePHPSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePHPSettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(phpPathTextfield))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(phpEnable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phpBrowseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(savePHPSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(phpPathTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phpBrowseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(phpEnable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(savePHPSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Sites");

        websiteTabPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        saveSites.setText("Save");
        saveSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSitesActionPerformed(evt);
            }
        });

        addNewSiteButton.setText("Add new site");
        addNewSiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewSiteButtonActionPerformed(evt);
            }
        });

        removeSiteButton.setText("Remove site");
        removeSiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSiteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(websiteTabPane)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(removeSiteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addNewSiteButton)
                                .addGap(15, 15, 15)
                                .addComponent(saveSites, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(websiteTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(saveSites, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeSiteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addNewSiteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Black List");

        jScrollPane3.setViewportView(blackListList);

        removeBlackListItemButton.setText("Remove");
        removeBlackListItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBlackListItemButtonActionPerformed(evt);
            }
        });

        saveBlackListButton.setText("Save");
        saveBlackListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBlackListButtonActionPerformed(evt);
            }
        });

        ipPart1.setName(""); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText(".");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText(".");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText(".");

        addBlackListItemButton.setText("Add");
        addBlackListItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBlackListItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(ipPart1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ipPart2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ipPart3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ipPart4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addBlackListItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(removeBlackListItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(saveBlackListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(13, 13, 13))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(removeBlackListItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveBlackListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ipPart1)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel13))
                            .addComponent(ipPart2)
                            .addComponent(ipPart4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ipPart3, javax.swing.GroupLayout.Alignment.LEADING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBlackListItemButton)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 260, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Settings", jPanel1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("IP");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Port");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Response");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("Request");

        responseField.setText("<html>");
        responseField.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        responseField.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        requestField.setText("<html>");
        requestField.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        requestField.setFocusable(false);
        requestField.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ipField.setText("<html>");
        ipField.setToolTipText("");
        ipField.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ipField.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        portField.setText("<html>");
        portField.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        portField.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ipField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(requestField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(responseField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jSeparator1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ipField, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addComponent(requestField)
                    .addComponent(responseField)
                    .addComponent(portField))
                .addGap(0, 0, 0))
        );

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jTabbedPane1.addTab("Connections", jPanel2);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mars Control Panel");

        versionLabel.setForeground(new java.awt.Color(255, 255, 255));
        versionLabel.setText("version 1.0.0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(versionLabel)
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(versionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getCheckBoxActionPerformed

    private void connectCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connectCheckBoxActionPerformed

    private void optionsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionsCheckBoxActionPerformed

    private void defaultFileTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultFileTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defaultFileTextFieldActionPerformed

    private void saveSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSitesActionPerformed
        try {
            boolean flag = false;
            for (int i = 0; i < websiteTabPane.getTabCount(); i++) {
                WebsitePanel panel = (WebsitePanel) (websiteTabPane.getComponentAt(i));
                Website site = null;
                for (int j = 0; j < Config.WEBSITES.size(); j++) {
                    site = Config.WEBSITES.get(j);
                    if (site.getId() == panel.getId()) {
                        flag = true;
                        break;
                    }
                }

                /*
                 if flag = true ,website already exists and is contained in the site object
                 */
                if (flag) {
                    site.setPort(panel.getPort());
                    site.setOnline(panel.isOnline());
                    site.setPath(panel.getPath());
                    site.setSsl(panel.isSSL());
                    site.setSslFile(panel.getSSLFile());
                    site.setSslPass(panel.getSSLPass());
                    websiteTabPane.setTitleAt(i, site.getId() + "::" + site.getPort());
                    try {
                        if (site.isOnline()) {
                            site.resume();
                        } else {
                            site.pause();
                        }
                    } catch (Exception e) {
                    }
                } else {
                    Website temp = new Website(panel.getPort(), panel.getPath(), panel.isSSL(), panel.isOnline(), panel.getSSLFile(), panel.getSSLPass());
                    websiteTabPane.setTitleAt(i, temp.getId() + "::" + temp.getPort());
                    if (temp.isOnline()) {
                        temp.start();
                    }
                    Config.WEBSITES.add(temp);
                }
                flag = false;
            }
            Config.saveChanges();
            JOptionPane.showMessageDialog(null, "Changes saved successfuly", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Something went wrong..", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveSitesActionPerformed

    private void removeDefaultFileNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDefaultFileNameButtonActionPerformed
        pageListModel.remove(defaultPageList.getSelectedIndex());
    }//GEN-LAST:event_removeDefaultFileNameButtonActionPerformed

    private void addDefaultFileNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDefaultFileNameButtonActionPerformed
        pageListModel.addElement(defaultFileTextField.getText());
        defaultFileTextField.setText("");
    }//GEN-LAST:event_addDefaultFileNameButtonActionPerformed

    private void saveDefaultNamesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDefaultNamesButtonActionPerformed
        Config.DEFAULT_PAGES.clear();
        for (int i = 0; i < pageListModel.getSize(); i++) {
            Config.DEFAULT_PAGES.add(pageListModel.getElementAt(i).toString());
        }
        try {
            Config.saveChanges();
            JOptionPane.showMessageDialog(null, "Changes saved successfuly", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_saveDefaultNamesButtonActionPerformed

    private void removeBlackListItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBlackListItemButtonActionPerformed
        blackListModel.remove(blackListList.getSelectedIndex());
    }//GEN-LAST:event_removeBlackListItemButtonActionPerformed

    private void saveBlackListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBlackListButtonActionPerformed
        Config.BLACK_LIST.clear();
        for (int i = 0; i < blackListModel.getSize(); i++) {
            Config.BLACK_LIST.add(blackListModel.getElementAt(i).toString());
        }
        try {
            Config.saveChanges();
            JOptionPane.showMessageDialog(null, "Changes saved successfuly", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_saveBlackListButtonActionPerformed

    private void addBlackListItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBlackListItemButtonActionPerformed
        if (ServerUtils.isNumeric(ipPart1.getText())
                && ServerUtils.isNumeric(ipPart2.getText())
                && ServerUtils.isNumeric(ipPart3.getText())
                && ServerUtils.isNumeric(ipPart4.getText())
                && Integer.parseInt(ipPart1.getText()) < 256 && Integer.parseInt(ipPart1.getText()) >= 0
                && Integer.parseInt(ipPart2.getText()) < 256 && Integer.parseInt(ipPart2.getText()) >= 0
                && Integer.parseInt(ipPart3.getText()) < 256 && Integer.parseInt(ipPart3.getText()) >= 0
                && Integer.parseInt(ipPart4.getText()) < 256 && Integer.parseInt(ipPart4.getText()) >= 0) {

            blackListModel.addElement(ipPart1.getText() + "." + ipPart2.getText() + "." + ipPart3.getText() + "." + ipPart4.getText());

        } else {
            JOptionPane.showMessageDialog(null, "The ip is not valid , please enter a valid ip.", "IP is not valid", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_addBlackListItemButtonActionPerformed

    private void saveMethodsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMethodsButtonActionPerformed
        Config.GET = getCheckBox.isSelected();
        Config.POST = postCheckBox.isSelected();
        Config.HEAD = headCheckBox.isSelected();
        Config.TRACE = traceCheckBox.isSelected();
        Config.CONNECT = connectCheckBox.isSelected();
        Config.PUT = putCheckBox.isSelected();
        Config.DELETE = deleteCheckBox.isSelected();
        Config.OPTIONS = optionsCheckBox.isSelected();

        try {
            Config.saveChanges();
            JOptionPane.showMessageDialog(null, "Changes saved successfuly", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Something went wrong..", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveMethodsButtonActionPerformed

    private void savePHPSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePHPSettingsActionPerformed
        Config.PHP_ENABLED = phpEnable.isSelected();
        Config.PHP_PATH = phpPathTextfield.getText();

        try {
            Config.saveChanges();
            JOptionPane.showMessageDialog(null, "Changes saved successfuly", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Something went wrong..", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_savePHPSettingsActionPerformed

    private void phpBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phpBrowseButtonActionPerformed
        JFileChooser chooser;
        if (Config.PHP_PATH != "") // if php path is set we set the choosers default directory the php path
        {
            chooser = new JFileChooser(Config.PHP_PATH);
        } else // else we point to the user's home directory
        {
            chooser = new JFileChooser();
        }

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            phpPathTextfield.setText(chooser.getSelectedFile().getAbsolutePath());
        }

    }//GEN-LAST:event_phpBrowseButtonActionPerformed

    private void addNewSiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewSiteButtonActionPerformed
        websiteTabPane.addTab("-1:(new site)", new WebsitePanel("default", 60000, false, false, Website.ID++, "", ""));
    }//GEN-LAST:event_addNewSiteButtonActionPerformed

    private void removeSiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSiteButtonActionPerformed

        int choise = JOptionPane.showConfirmDialog(null, "Are you sure you want to remove this website?", "Remove site.", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (choise == JOptionPane.YES_OPTION) {
            int pos = -1;
            for (int i = 0; i < Config.WEBSITES.size(); i++) {
                if (websiteTabPane.getTitleAt(websiteTabPane.getSelectedIndex()).split(":")[0].equals(String.valueOf(Config.WEBSITES.get(i).getId()))) {
                    pos = i;
                    break;
                }
            }

            if (pos != -1) {
                Config.WEBSITES.remove(pos);
            }
            websiteTabPane.remove(websiteTabPane.getSelectedIndex());

            try {
                Config.saveChanges();
                JOptionPane.showMessageDialog(null, "Changes saved successfuly", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Something went wrong..", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_removeSiteButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBlackListItemButton;
    private javax.swing.JButton addDefaultFileNameButton;
    private javax.swing.JButton addNewSiteButton;
    private javax.swing.JList blackListList;
    private javax.swing.JButton closeButton;
    private javax.swing.JCheckBox connectCheckBox;
    private javax.swing.JTextField defaultFileTextField;
    private javax.swing.JList defaultPageList;
    private javax.swing.JCheckBox deleteCheckBox;
    private javax.swing.JCheckBox getCheckBox;
    private javax.swing.JCheckBox headCheckBox;
    private javax.swing.JLabel ipField;
    private javax.swing.JTextField ipPart1;
    private javax.swing.JTextField ipPart2;
    private javax.swing.JTextField ipPart3;
    private javax.swing.JTextField ipPart4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox optionsCheckBox;
    private javax.swing.JButton phpBrowseButton;
    private javax.swing.JCheckBox phpEnable;
    private javax.swing.JTextField phpPathTextfield;
    private javax.swing.JLabel portField;
    private javax.swing.JCheckBox postCheckBox;
    private javax.swing.JCheckBox putCheckBox;
    private javax.swing.JButton removeBlackListItemButton;
    private javax.swing.JButton removeDefaultFileNameButton;
    private javax.swing.JButton removeSiteButton;
    private javax.swing.JLabel requestField;
    private javax.swing.JLabel responseField;
    private javax.swing.JButton saveBlackListButton;
    private javax.swing.JButton saveDefaultNamesButton;
    private javax.swing.JButton saveMethodsButton;
    private javax.swing.JButton savePHPSettings;
    private javax.swing.JButton saveSites;
    private javax.swing.JCheckBox traceCheckBox;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JTabbedPane websiteTabPane;
    // End of variables declaration//GEN-END:variables
}
